language: python
python:
- '3.6'
- '3.7'
before_install:
- export MPLBACKEND=agg
- pip install --upgrade pip
install:
- pip install flake8
- pip install .
script:
- flake8 funfolding
- python setup.py test
deploy:
  provider: pypi
  user: "__token__"
  skip_cleanup: true
  distributions: sdist
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.7"
  password:
    secure: RlZg6qNTs8GU0JZD3h1RBKOFDeCkZQgX3YohoVr8/WislImaslb2HzvTjSq8cO9IlRNIQ+O1728vNod3tokMDOT1w3bv6y9BDrQCgWveHyjhBmXPa47G9ZISGFczea66rNcGd6bNX4l5FreMFS8A1wNkNmF8QWzueLHQOFQn8cWmfYPf8dVPkvtDNTSUEfIXh2lPy9RYdXsrWsucdHqL5qVeTuNW2g9eYkBY0QGOjd5aqMpdUouDgYx2ztTNpfHdfytX5uO4u9pzYjTWZzulnN0XOQUySnGeMyreRbpnd3C6q7CDLQ02pckmLt0S7yscRcShN4FfvZf1lk/zaHQG2SbpwCdN34EcLcb9iuDdcNhwpCkLCfHTCsdPWbmDbTjeZ0+VllTFCIqT25RoSLLorpjGCvaN2Gnrj5g/N8qOvrS6+dyk9Z4ZIPFS7k2pPBMmTV9hZEqTUy+cEkKJKLygPDo1b081WGzAUOaA4HAwoNB8PKfUAY03Al+NPYPd0wWa7Rre97u0kX0T7DM2HmLa9htZUlqrQlHuSszbDdtKb+b3+fZWVGq4bz+ya8guBYNdtoq+B0GoZ9Fog9BqkSHx40aTWgFYd+LwMb5NHpC2cr4Vp7Oo3bMlCcupBKNb4K/MxxtS3KpN7HJYTXJdjtgwjy5ndxlwqvgY458ESWY8kss=
