language: python

python:
  - '3.5'
  - '3.6'
  - '2.7'

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sudo rm -rf /dev/shm
  - sudo ln -s /run/shm /dev/shm
  - pip install --upgrade pip

install:
  - pip install flake8
  - pip install https://github.com/dfm/emcee/archive/master.tar.gz
  - pip install .

script:
  - flake8 funfolding
  - python setup.py test

deploy:
  provider: pypi
  user: tudo-app
  skip_cleanup: true
  distributions: sdist
  on:
    branch: master
    tags: true
    condition: $TRAVIS_PYTHON_VERSION = "3.6"
  password:
    secure: NMxrfT2lnJQELuFER0ZV+lCeD4wwVgiG3Q42udrSGc8PX5I5ePBPFu0m9srHjhYwTXJ9Gmj+p+2Cw21X8aG/ZA0wcZVsALsJE1WWlJh5FV71RYv8qHi4N3xHKhsqnqJC9hvtbWKuRbizwPUqwkJpPNodOWpIhQvsQVtS6gBooAsYSz44Wv+wIzKGOur2LNUShBmiUKAB79fxyyxWtFYHUa32KUMTz1VjPe1a23CXYBbKHJZ+1wNHc6GKJrRDJBXv2Z6bCGKywTxMoGGRly2Yum8mxYrd10h3neD5UJPW+fxb4bBDXznTnGd54m3GRPrXrd+YvHc4ZlKkohjD1pU3D9N2HT5t2++BNHnMDN+0vgJDV3ns1prHAl4BAq5tnS9RGqC04VMB+g7lDEJ/77vu1X7EG0BHnMx/ZAnZJI+LgxjM578w2zvEtV93GWcjCRfBiPXKlv+BMll5VtwtImfZaUZWU5uCLZ8cWD9FGOBZNISwR2f8NzJ2U5tBup5ZEN45pOqtlUSLBXpRGMStnqf2+l189dICgrn23mKB1T3hYdJZnq24UOa9wm3tO1cEx2xboxxbyIRzktw7HP6J+3MWy+J5eFiCu40+uftPTclbgMYDAvqn859dUJ6x8Kf3443tmV0GpLpD0XiTCgfkEOfVhCcX0btdiYRaFGS23kT+LtU=
